### ISSUE TITLE
no module named 'models.tmrnetplus_model'

### ISSUE THREAD

**Issue by qiufengyuzhi** [chengeng0613/HLNet#1]
When I execute the train_track2.sh file, an error occurs. What can I do to resolve it

**Comment by chengeng0613** [comment]
你好，实在抱歉，最近比较忙，刚看到邮件。
关于你提到的问题我已经更新了我在Github上的代码，应该解决了这个问题，我在我的电脑上重新调试了。
你在运行代码前需要对训练集进行裁剪，裁剪的代码在/data/gen_track.py里面。
祝你学业顺利。

I'm really sorry, I've been busy recently and just saw the email.
Regarding the problem you mentioned, I have updated my code on Github,
which should solve the problem. I re-debugged it on my computer.
You need to crop the training set before running the code. The cropping
code is in /data/gen_track.py.
I wish you good academic success.

qiufengyuzhi ***@***.***> 于2024年10月16日周三 14:52写道：

**Comment by qiufengyuzhi** [comment]
谢谢陈老师，代码问题之前已经解决了，感谢您的回复，再次祝您身体健康，工作顺利
















在 2024-10-27 19:22:26，"ChenGeng" ***@***.***> 写道：

你好，实在抱歉，最近比较忙，刚看到邮件。
关于你提到的问题我已经更新了我在Github上的代码，应该解决了这个问题，我在我的电脑上重新调试了。
你在运行代码前需要对训练集进行裁剪，裁剪的代码在/data/gen_track.py里面。
祝你学业顺利。

I'm really sorry, I've been busy recently and just saw the email.
Regarding the problem you mentioned, I have updated my code on Github,
which should solve the problem. I re-debugged it on my computer.
You need to crop the training set before running the code. The cropping
code is in /data/gen_track.py.
I wish you good academic success.

qiufengyuzhi ***@***.***> 于2024年10月16日周三 14:52写道：
